# Generated by Django 2.2.4 on 2019-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20190912_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
